include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
    - tool/**
  errors:
    subtype_of_sealed_class: ignore
    prefer_initializing_formals: ignore
    use_null_aware_elements: ignore
  language:
    strict-casts: true

linter:
  rules:
    - avoid_print
    - prefer_single_quotes
    - prefer_const_constructors_in_immutables
